# NumPy - Array Attributes


In [1]:
import numpy as np

array = np.array([[1,2,3],[4,5,6]])
print(array)

# CHECK DIMENSION OF THE ARRAY - ndim
print(array.ndim)

# CHECK THE SHAPE OF THE ARRAY- shape
print(array.shape)

# CHECK THE SIZE OF THE ARRAY - size
print(array.size)

# CHECK THE STEP DIFFERENCE BETWEEN EACH ROW AND COLUMN - strides
print(array.strides)

# CHECK THE DATA TYPE OF THE ARRAY - dtype
print(array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
(24, 8)
int64


# NumPy - Create a Basic Array

In [2]:
# USING THE np.array() method
np_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np_array)
print()

# USING THE np.zeros() method
zero = np.zeros((3,4))
# zero = np.zeros((3,4), dtype = np.int64) # use dtype parameter to change the data type 
print(zero)
print()

# USING THE np.ones() method
one = np.ones((4,3))
print(one)
print()

# USING THE np.eye() method
identity = np.eye(3)
print(identity)
print()

# USING THE np.full() method
constant = np.full((3,3), 7)
print(constant)
print()

# USING THE np.empty() method - fills with random values
empt = np.empty((3,3))
print(empt)
print()

# USING THE np.arange() method - last not included
custom_range = np.arange(1,11,2)
print(custom_range)
print()

# USING THE np.linspace() method - last included
linarray = np.linspace(1,2,num=5)
print(linarray)
print()

# USING THE np.random.random() method - generate random number between 0 and 1; not include 1
random = np.random.random((3,4))
print(random)
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[7 7 7]
 [7 7 7]
 [7 7 7]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[1 3 5 7 9]

[1.   1.25 1.5  1.75 2.  ]

[[0.15149492 0.7152959  0.71658771 0.65148064]
 [0.30124848 0.41382652 0.7325433  0.43387224]
 [0.44887261 0.7365172  0.69550046 0.8878795 ]]



# NumPy - Array Indexing

In [21]:
array = np.array([[1,2,3],
                  [4,5,6]])

# ACCESS A SINGLE ELEMENT
element = array[0, 2]
# array[0, 2] = 7
print(element)

# ROW INDEXING
row = array[1]
print(row)

# COLUMN INDEXING
col = array[0,2]
print(col)
print()

# NEGATIVE INDEXING
print(array[-1,-2])
print()

# ROW SLICING
row_slice = array[:] # Select all the rows
print(row_slice)
print()

specified_row = array[0:1] # Select the first row
print(specified_row)
print()

# COLUMN SLICING
col_slicing = array[:, :] # Select all the columns
print(col_slicing)
print()

specified_col = array[:, 0:2] # Selects the first two columns
print(specified_col)
print()

3
[4 5 6]
3

5

[[1 2 3]
 [4 5 6]]

[[1 2 3]]

[[1 2 3]
 [4 5 6]]

[[1 2]
 [4 5]]



# NumPy - Adavnced Array Indexing

In [25]:
arr = np.array([10,20,30,40,50,60,70])

# INTEGER INDEXING - returns one dimensional array
selected_elements = arr[[0,3,5]]
print(selected_elements)
print()

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

row_elements = [0,1]
col_elements = [0,2]

elements = arr2d[row_elements, col_elements]
print(elements)
print()

[10 40 60]

[1 6]



In [35]:
# BOOLEAN INDEXING - MASKING
data = np.array([[1, 2], [3, 4], [5, 6]])

# STEP 1: FIRST FILTER THE DATA
filtered_data = data > 3 # Returns a boolen array
# filtered_data = (data > 2) & (data < 6)
print(filtered_data)
print()

# STEP 2: SELECT THE DATA
selected_data = data[filtered_data] # Returns always a one dimensional array
print(selected_data)
print()

[[False False]
 [False  True]
 [ True  True]]

[4 5 6]



In [6]:
ar = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[7, 8, 9], [10, 11, 12]]])
print(ar[0, 0]) # Output: [1,2,3]
print(ar[0, 1]) # Output: [4,5,6]
print()

print(ar[1,0]) # Output: [7,8,9]
print(ar[1,1]) # Output: [10,11,12]
print()

print(ar[0,0,0]) # Output: 1
print(ar[0,0,1]) # Output: 2
print(ar[0,0,2]) # Output: 3
print()

print(ar[0,1,0]) # Output: 4
print(ar[0,1,1]) # Output: 5
print(ar[0,1,2]) # Output: 6
print()

print(ar[1,0,0]) # Output: 7
print(ar[1,0,1]) # Output: 8
print(ar[1,0,2]) # Output: 9
print()

print(ar[1,1,0]) # Output: 10
print(ar[1,1,1]) # Output: 11
print(ar[1,1,2]) # Outptu: 12
print()

[1 2 3]
[4 5 6]

[7 8 9]
[10 11 12]

1
2
3

4
5
6

7
8
9

10
11
12



In [7]:
print(ar[0:1, 0:1, 0:1]) # Output: [[[1]]]
print(ar[:1, 0]) # Outptu: [[1 2 3]]

[[[1]]]
[[1 2 3]]


# NumPy - Data Type

In [18]:
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

data = np.array([1,2,3])

# Check the data type
print(f"Data Type: {data.dtype}")

strings = np.array(["Asaduzzaman", "Alice", "Smith"])
print(f"Data Type: {strings.dtype}")

boolean = np.array([True, False, False, True, True])
print(f"Data Type: {boolean.dtype}")

floats = np.array([7.8,2.5,8.9])
print(f"Data Type: {floats.dtype}")

mix = np.array([True, 1,3,5,7, 5.7, "Asaduzzaman"])
print(f"Data Type: {mix.dtype}")
print(mix)
print()

mix_1 = np.array([True, 1,3,5,7, 5.7])
print(f"Data Type: {mix_1.dtype}")
print(mix_1)
print()

mix_2 = np.array([True, 1,3,5,7, False])
print(f"Data Type: {mix_2.dtype}")
print(mix_2)

Data Type: int64
Data Type: <U11
Data Type: bool
Data Type: float64
Data Type: <U32
['True' '1' '3' '5' '7' '5.7' 'Asaduzzaman']

Data Type: float64
[1.  1.  3.  5.  7.  5.7]

Data Type: int64
[1 1 3 5 7 0]


In [38]:
# Create Array with Defined Data Type - Type Conversion
integer = np.array([1.3, 3.4, 5.7, 6.6], dtype = np.int64)
print(f"Data Type: {integer.dtype}")
print(integer)
print()

floats = np.array([1,2,3,4,5], dtype = np.float64)
print(f"Data Type: {floats.dtype}")
print(floats)
print()

string = np.array([1,2,3,4,0,6], dtype = 'U')
print(f"Data Type: {string.dtype}")
print(string)
print()

boolean = np.array([1,0,1,0,1,1,0,0,1], dtype = 'bool')
print(f"Data Type: {boolean.dtype}")
print(boolean)
print()

complex_num = np.array([1,2,3,4,5], dtype = 'complex')
print(f"Data Type: {complex_num.dtype}")
print(complex_num)
print()

Data Type: int64
[1 3 5 6]

Data Type: float64
[1. 2. 3. 4. 5.]

Data Type: <U1
['1' '2' '3' '4' '0' '6']

Data Type: bool
[ True False  True False  True  True False False  True]

Data Type: complex128
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]



In [48]:
# Converting Data Type on Exxisting Array - astype() method
numbers = np.array([1,2,3,4,5,6,7])

# Convert to float
float_number = numbers.astype(np.float64)
print(f"Data Type: {float_number.dtype}")
print(float_number)
print()

# Convert to string
float_number = numbers.astype('U')
print(f"Data Type: {float_number.dtype}")
print(float_number)
print()

# Convert to boolean
float_number = numbers.astype(bool)
print(f"Data Type: {float_number.dtype}")
print(float_number)
print()

# Convert to complex
float_number = numbers.astype(complex)
print(f"Data Type: {float_number.dtype}")
print(float_number)
print()

Data Type: float64
[1. 2. 3. 4. 5. 6. 7.]

Data Type: <U21
['1' '2' '3' '4' '5' '6' '7']

Data Type: bool
[ True  True  True  True  True  True  True]

Data Type: complex128
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j]



# NumPy - Copy vs View
- Copy: changes in the original does not affect the copy, and vice-versa, and owns the data
- View: changes in the original also changes the view, and vice-versa, does not own the data

In [52]:
# Original version
original = np.array([1,2,3,4,5,6,7])

# Create a copy of the original one
copy = original.copy()

print(f"Original Version: {original}")
print(f"Copy version: {copy}")
print()

# Now, change the original version
original[4] = 77

print(f"Original Version: {original}")
print(f"Copy version: {copy}")
print()

# Now, change the copy version
copy[3] = 67

print(f"Original Version: {original}")
print(f"Copy version: {copy}")
print()

Original Version: [1 2 3 4 5 6 7]
Copy version: [1 2 3 4 5 6 7]

Original Version: [ 1  2  3  4 77  6  7]
Copy version: [1 2 3 4 5 6 7]

Original Version: [ 1  2  3  4 77  6  7]
Copy version: [ 1  2  3 67  5  6  7]



In [60]:
# Original version
original = np.array([1,3,5,7,9])
# Create a view of the original version
view = original.view()

print(f"Original Version: {original}")
print(f"View version: {view}")
print()

# Now, change in the original version
original[2] = 6

print(f"Original Version: {original}")
print(f"View version: {view}")
print()

# Now, change in the view
view[2] = 77

print(f"Original Version: {original}")
print(f"View version: {view}")
print()

Original Version: [1 3 5 7 9]
View version: [1 3 5 7 9]

Original Version: [1 3 6 7 9]
View version: [1 3 6 7 9]

Original Version: [ 1  3 77  7  9]
View version: [ 1  3 77  7  9]



In [61]:
# Check if an array owns the data or not
students = np.array(["Asaduzzaman", "Alice", "Smith", "Bob"])

students_copy = students.copy()
students_view = students.view()

print(students_copy.base) # Returns None if it owns the data
print(students_view.base) # Returns the reference array

None
['Asaduzzaman' 'Alice' 'Smith' 'Bob']


# NumPy - Array Shape

In [66]:
# Get the shape of an array
number = np.array([1,2,3])
print(f"Shape: {number.shape}")
print()

arr2D = np.array([[1,2],[3,4]])
print(f"Shape: {arr2D.shape}")
print()

# Define an array with dimension
nd_arr = np.array(1, ndmin = 3)
print(f"Shape: {nd_arr.shape}")
print(nd_arr)
print()

Shape: (3,)

Shape: (2, 2)

Shape: (1, 1, 1)
[[[1]]]



# NumPy - Reshapes Array
- Change the shape of the array
- Returns view, not a copy

In [2]:
arr1D = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr1D)
print(f"Shape: {arr1D.shape}")
print()
# Convert the array to 2D
arr2D = arr1D.reshape(4,3)
print(arr2D)
print(f"Shape: {arr2D.shape}")
print()

# Convert the array to 3D
arr3D = arr1D.reshape(2,3,2)
# arr3D = arr1D.reshape(2,3,-1) # The negative dimension auto identify the dimension based on the array size and other given dimension
print(arr3D)
print(f"Shape: {arr3D.shape}")
print()

# Convert the array to 4D
arr4D = arr1D.reshape(1,2,3,2)
print(arr4D)
print(f"Shape: {arr4D.shape}")
print()

# Reshape to 1D
array1D = arr4D.reshape(-1)
print(array1D)
print(f"Shape: {array1D.shape}")
print()

# Alternative way to reshape into 1D - flat attribute, flatten() method
print(arr4D.flat[0]) # Returns iterator
print(arr3D.flatten()) # Returns copy

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Shape: (2, 3, 2)

[[[[ 1  2]
   [ 3  4]
   [ 5  6]]

  [[ 7  8]
   [ 9 10]
   [11 12]]]]
Shape: (1, 2, 3, 2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

1
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# NumPy - Array Iterating

In [9]:
#  Using loop
# 1D array
marks = np.array([67, 88, 91, 56, 40, 93])

for x in marks:
    print(x)
print()

# 2D Array
marks2D = np.array([[77,87,65],[97,90,89]])

for x in marks2D:
    # print(x)
    for y in x:
        print(y)
print()

# 3D array
marks3D = np.array([[[81,85,87],[67,60,63]],[[81,87,89],[90,93,97]]])

for x in marks3D:
    # print(x)
    for y in x:
        # print(y)
        for z in y:
            print(z)

67
88
91
56
40
93

77
87
65
97
90
89

81
85
87
67
60
63
81
87
89
90
93
97


In [12]:
# Using nditer() method
for item in np.nditer(marks):
    print(item)
print()

for item in np.nditer(marks2D):
    print(item)
print()

for item in np.nditer(marks3D):
    print(item)

67
88
91
56
40
93

77
87
65
97
90
89

81
85
87
67
60
63
81
87
89
90
93
97


In [31]:
# Iterating Array With Different Data Types
for item in np.nditer(marks, flags=['buffered'], op_dtypes=['S']):
    print(item)

np.bytes_(b'67')
np.bytes_(b'88')
np.bytes_(b'91')
np.bytes_(b'56')
np.bytes_(b'40')
np.bytes_(b'93')


In [34]:
# Iterating With Different Step Size
for item in np.nditer(marks[::2]):
    print(item)
print()
for item in np.nditer(marks2D[:, ::2]):
    print(item)

67
91
40

77
65
97
89


In [39]:
# Using the np.ndenumerate()
for index, item in np.ndenumerate(marks):
    print(f"Index {index}: {item}")
print()

for index, item in np.ndenumerate(marks2D):
    print(f"Index {index}: {item}")
print()

for index, item in np.ndenumerate(marks3D):
    print(f"Index {index}: {item}")

Index (0,): 67
Index (1,): 88
Index (2,): 91
Index (3,): 56
Index (4,): 40
Index (5,): 93

Index (0, 0): 77
Index (0, 1): 87
Index (0, 2): 65
Index (1, 0): 97
Index (1, 1): 90
Index (1, 2): 89

Index (0, 0, 0): 81
Index (0, 0, 1): 85
Index (0, 0, 2): 87
Index (0, 1, 0): 67
Index (0, 1, 1): 60
Index (0, 1, 2): 63
Index (1, 0, 0): 81
Index (1, 0, 1): 87
Index (1, 0, 2): 89
Index (1, 1, 0): 90
Index (1, 1, 1): 93
Index (1, 1, 2): 97
