1️⃣ Array Creation
------------------
Create a 1-D NumPy array of integers from 1 to 20.
Then reshape it to (4, 5).

In [7]:
import numpy as np

array = np.arange(1,21)
print(array)
print()

# Resahpe it to (4,5)
reshaped = np.reshape(array,(4,5))
print(reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


2️⃣ Array Statistics
--------------------
Compute mean, median, standard deviation, variance, and sum
for an array of random numbers.

In [17]:
array = np.random.random((4,4))
print(array)
print()

print(np.mean(array))
print(np.median(array))
print(np.std(array))
print(np.var(array))
print(np.sum(array))


[[0.63675611 0.50829685 0.98023242 0.96575518]
 [0.03496463 0.66852474 0.80186636 0.84553121]
 [0.82362949 0.82811129 0.34440495 0.11292126]
 [0.90666333 0.30686013 0.91661745 0.31015337]]

0.6244555480623694
0.735195546316269
0.3033553573955408
0.09202447286057629
9.99128876899791


3️⃣ Array Slicing
-----------------
Given a 5×5 array, extract the center 3×3 matrix.

In [20]:
array = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(array)
print()

center = array[1:4,1:4]
print(center)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


4️⃣ Indexing with Conditions
----------------------------
From an array arr = np.arange(10, 51), extract numbers divisible by 3.


In [23]:
array = np.arange(10, 51)
print(array)
print()

mask = array % 3 == 0
print(array[mask])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

[12 15 18 21 24 27 30 33 36 39 42 45 48]


5️⃣ Broadcasting
----------------
Create a 3×3 matrix A and add a 1-D array b to each row.

In [34]:
A = np.arange(1,10)
print(A.shape)

# Resahpe by 3x3
reshape = np.reshape(A, (3,3))
print(reshape.shape)
print(reshape)
print()

b = np.array([1,2,3])
print(b.shape)
print()

print(reshape + b)

(9,)
(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]

(3,)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]



6️⃣ Stacking Arrays
-------------------
Horizontally and vertically stack two random 3×3 arrays.

In [49]:
arr1 = np.random.random((3,3))
arr2 = np.random.random((3,3))
print(arr1.shape)
print(arr2.shape)
print()

print(arr1)
print()

print(arr2)
print()

# Horizontally stack
stack_h = np.hstack((arr1,arr2))

# Vertically stack
stack_v = np.vstack((arr1,arr2))

print(stack_h)
print()

print(stack_v)
print()

(3, 3)
(3, 3)

[[0.56346454 0.69531137 0.83207329]
 [0.75019347 0.00123696 0.36848013]
 [0.66475544 0.01101487 0.51128973]]

[[0.20322965 0.5146599  0.53593285]
 [0.28302423 0.21051829 0.76565591]
 [0.0512674  0.13067201 0.05850134]]

[[0.56346454 0.69531137 0.83207329 0.20322965 0.5146599  0.53593285]
 [0.75019347 0.00123696 0.36848013 0.28302423 0.21051829 0.76565591]
 [0.66475544 0.01101487 0.51128973 0.0512674  0.13067201 0.05850134]]

[[0.56346454 0.69531137 0.83207329]
 [0.75019347 0.00123696 0.36848013]
 [0.66475544 0.01101487 0.51128973]
 [0.20322965 0.5146599  0.53593285]
 [0.28302423 0.21051829 0.76565591]
 [0.0512674  0.13067201 0.05850134]]



7️⃣ Matrix Multiplication
-------------------------
Generate two compatible matrices A and B.
Compute both A @ B and B @ A, and check if multiplication is commutative.

In [52]:
array1 = np.array([[1,2,3]])
array2 = np.array([[2,4],[6,8],[10,12]])

print(array1.shape)
print(array2.shape)

# array1 @ array2
print(array1 @ array2)
print()

# array2 @ array1
# print(array2 @ array1) # raise an error
print()

(1, 3)
(3, 2)
[[44 56]]




8️⃣ Normalization
-----------------
Given a random 1-D array, normalize it to the range 0–1.  
Basic Syntax: normalized = a + ( (data - np.min(data)) * (b - a) ) / (np.max(data) - np.min(data)); where a, b the ranges

In [55]:
array = np.random.randint(1,100,10)
print(array)
print()

# Range a = 0 - b = 1
normalized = 0 + ((array - np.min(array)) * (1 - 0)) / (np.max(array) - np.min(array))
print(normalized)

[ 3 33 10 22 94 56 69 77 49 58]

[0.         0.32967033 0.07692308 0.20879121 1.         0.58241758
 0.72527473 0.81318681 0.50549451 0.6043956 ]


9️⃣ Random Sampling
-------------------
Generate a 5×5 matrix with random integers 0–100.
Replace all numbers greater than 50 with 50.

In [62]:
array = np.random.randint(0,100,25)
print(array.shape)

reshaped = np.reshape(array, (5,5))
print(reshaped.shape)
print()

print(array)
print(reshaped)
print()

mask = reshaped > 50
reshaped[mask] = 50
print(reshaped)

(25,)
(5, 5)

[35 46 16 97 38 18  5 51 37 53 89  1  7 99 45 15 47 25 40 22 20 79 90 93
 42]
[[35 46 16 97 38]
 [18  5 51 37 53]
 [89  1  7 99 45]
 [15 47 25 40 22]
 [20 79 90 93 42]]

[[35 46 16 50 38]
 [18  5 50 37 50]
 [50  1  7 50 45]
 [15 47 25 40 22]
 [20 50 50 50 42]]


🔟 Performance
--------------
Compare time taken to sum 1,000,000 numbers using:
- A pure Python list
- A NumPy array

(Use %timeit for performance measurement.)

In [72]:
lst = list(range(1_000_000))
array = np.arange(1_000_000)

# Sum of list
%timeit sum(lst)
print()

# Sum of array
%timeit np.sum(array)
print()

print(np.sum(array))

19 ms ± 2.48 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

1.06 ms ± 27.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

499999500000
